CREATE TABLE IF NOT EXISTS `t_table`  (
  `c_bit` bit(1) NULL DEFAULT NULL,
  `c_char` char(0) NULL DEFAULT NULL,
  `c_date` date NULL DEFAULT NULL,
  `c_decimal` decimal(10, 0) NULL DEFAULT NULL,
  `c_double` double NULL DEFAULT NULL,
  `c_float` float NULL DEFAULT NULL,
  `c_int` int(11) NULL DEFAULT NULL,
  `c_integer` int(11) NULL DEFAULT NULL,
  `c_numeric` decimal(10, 0) NULL DEFAULT NULL,
  `c_real` double NULL DEFAULT NULL,
  `c_smallint` smallint(6) NULL DEFAULT NULL,
  `c_time` time(0) NULL DEFAULT NULL,
  `c_timestamp` timestamp(0) NULL DEFAULT NULL,
  `c_varchar` varchar(0) NULL DEFAULT NULL,
  ) ;