DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR(255));
insert into TEST(id, name) values (1,'1');
insert into TEST(id, name) values (2,'1');
insert into TEST(id, name) values (3,'1');
insert into TEST(id, name) values (4,'1');
insert into TEST(id, name) values (5,'1');
insert into TEST(id, name) values (6,'1');
insert into TEST(id, name) values (7,'1');
insert into TEST(id, name) values (8,'1');
insert into TEST(id, name) values (9,'1');
insert into TEST(id, name) values (10,'1');
insert into TEST(id, name) values (11,'1');
insert into TEST(id, name) values (12,'1');
insert into TEST(id, name) values (13,'1');
insert into TEST(id, name) values (14,'1');
insert into TEST(id, name) values (15,'1');
insert into TEST(id, name) values (16,'1');
insert into TEST(id, name) values (17,'1');
insert into TEST(id, name) values (18,'1');
insert into TEST(id, name) values (19,'1');
insert into TEST(id, name) values (20,'1');
insert into TEST(id, name) values (21,'1');
