DROP TABLE IF EXISTS TEST_TABLE;
CREATE TABLE TEST_TABLE
(
    ID   INT PRIMARY KEY,
    CODE VARCHAR(255) COMMENT '编码',
    NAME VARCHAR(255) COMMENT '名称'
);
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (1,'CODE1','NAME1');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (2,'CODE2','NAME2');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (3,'CODE3','NAME3');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (4,'CODE4','NAME4');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (5,'CODE5','NAME5');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (6,'CODE6','NAME6');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (7,'CODE7','NAME7');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (8,'CODE8','NAME8');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (9,'CODE9','NAME9');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (10,'CODE1','NAME1');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (11,'CODE1','NAME1');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (12,'CODE2','NAME2');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (13,'CODE3','NAME3');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (14,'CODE4','NAME4');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (15,'CODE5','NAME5');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (16,'CODE6','NAME6');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (17,'CODE7','NAME7');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (18,'CODE8','NAME8');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (19,'CODE9','NAME9');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (20,'CODE1','NAME1');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (21,'CODE1','NAME1');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (22,'CODE2','NAME2');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (23,'CODE3','NAME3');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (24,'CODE4','NAME4');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (25,'CODE5','NAME5');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (26,'CODE6','NAME6');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (27,'CODE7','NAME7');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (28,'CODE8','NAME8');
INSERT INTO TEST_TABLE(ID,CODE,NAME) VALUES (29,'CODE9','NAME9');
